// Eyedeea Photos PM2 Configuration
// This file is generated by the installation script with platform-specific paths

// Platform detection
const isWindows = process.platform === 'win32';
const path = require('path');
const os = require('os');

// Determine log directory based on platform
let logDir;
if (isWindows) {
  // Windows: Use AppData\Local for centralized logging
  const appDataLocal = process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local');
  logDir = path.join(appDataLocal, 'EyediaTech', 'EyedeeaPhotos', 'logs');
} else {
  // Linux: Use /var/log for centralized logging
  logDir = '/var/log/EyediaTech/EyedeeaPhotos';
}

module.exports = {
  apps: [{
    name: 'Eyedeea Photos',
    script: '/var/www/html/EyedeeaPhotos/node_modules/eyedeeaphotos/server/app.js',
    cwd: '/var/www/html/EyedeeaPhotos/node_modules/eyedeeaphotos',
    autorestart: true,
    env: {
      EYEDEEA_KEY: process.env.EYEDEEA_KEY || '$EYEDEEA_KEY'
    },
    // PM2-specific logs (separate from application logs)
    error_file: path.join(logDir, 'pm2_error.log'),
    out_file: path.join(logDir, 'pm2_app.log'),
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    
    // Additional PM2 settings
    instances: 1,
    exec_mode: 'fork',
    merge_logs: true,
    max_memory_restart: '500M'
  }]
};